spring.application.name=AutoEscolaN116
server.port=8080
spring.profiles.active=dev
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.mvc.problemdetails.enabled=true
# --- Web ---
spring.web.error.include-stacktrace=never
# --- Datasource ---
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
# --- JPA ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=validate
# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.connect-retries=3
# --- OTHERS ---
spring.data.web.pageable.one-indexed-parameters=true
api.security.token.secret=${JWT_SECRET:0123456789}
# RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbit.password=guest
# JAVA EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cemoliveir@gmail.com
# GMAIL - Senha App - Segurança -> Verificação em duas etapas
spring.mail.password=kvdg zfvg fire gqqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
