spring:
  application:
    name: AutoEscolaN116

  profiles:
    active: "dev"

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  mvc:
    problemdetails:
      enabled: true

  web:
    error:
      include-stacktrace: never

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    connect-retries: 3

  data:
    web:
      pageable:
        one-indexed-parameters: true

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT:8080}

api:
  security:
    token:
      secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    "[springframework.security]": DEBUG

app:
  rabbit:
    lesson:
      exchange: lesson.exchange
      queue: lesson.scheduled
      routing-key: lesson.scheduled