spring.application.name=AutoEscolaN116
server.port=8080
spring.profiles.active=dev
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.mvc.problemdetails.enabled=true
# --- Web ---
spring.web.error.include-stacktrace=never
# --- Datasource ---
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
# --- JPA ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=validate
# --- FLYWAY ---
spring.flyway.enabled=true
spring.flyway.connect-retries=3
# --- OTHERS ---
spring.data.web.pageable.one-indexed-parameters=true
api.security.token.secret=${JWT_SECRET:0123456789}